routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['revalidate','auth']], function(){
	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index');
	Route::get('/dashboard', 'HomeController@index');


    // project
    Route::resource('project', 'ErpProjectController');
    Route::get('deleteProjectView/{id}', 'ErpProjectController@deleteProjectView');
    Route::get('deleteProject/{id}', 'ErpProjectController@deleteProject');

//Chart of Accounts Category
    Route::resource('account-category', 'ErpAccountsCategoryController');
    Route::get('deleteAccountCategoryView/{id}', 'ErpAccountsCategoryController@deleteAccountCategoryView');
    Route::get('deleteAccountCategory/{id}', 'ErpAccountsCategoryController@deleteAccountCategory');

//chart of Accounts Class
    Route::resource('account-class', 'ErpAccountsClassController');
    Route::get('deleteAccountClassView/{id}', 'ErpAccountsClassController@deleteAccountClassView');
    Route::get('deleteAccountClass/{id}', 'ErpAccountsClassController@deleteAccountClass');

// Chart of Accounts
    Route::get('account-list', 'ErpChartOfAccountsController@accountList');
    Route::get('add-new-coa', 'ErpChartOfAccountsController@addNewCoa');
    Route::post('save-coa-data', 'ErpChartOfAccountsController@saveCoaData');
    Route::get('edit-coa/{id}', 'ErpChartOfAccountsController@editCoa');
    Route::post('editCoa', 'ErpChartOfAccountsController@editCoa');


//Client route
    Route::resource('client', 'ErpClientController');
    Route::get('deleteClientView/{id}', 'ErpClientController@deleteClientView');
    Route::get('deleteClient/{id}', 'ErpClientController@deleteClient');

// Role route
    Route::resource('role', 'ErpRoleController');
    Route::get('deleteRoleView/{id}', 'ErpRoleController@deleteRoleView');
    Route::get('deleteRole/{id}', 'ErpRoleController@deleteRole');
    Route::get('assign-permission/{role_id}', 'ErpRoleController@assignPermission');
    Route::post('role_permission_store', 'ErpRoleController@rolePermissionStore');

// User route
    Route::resource('user', 'ErpUserController');
    Route::get('deleteUserView/{id}', 'ErpUserController@deleteUserView');
    Route::get('deleteUser/{id}', 'ErpUserController@deleteUser');

//chart of Accounts Period
    Route::resource('period', 'ErpPeriodController');
    Route::get('deletePeriodView/{id}', 'ErpPeriodController@deletePeriodView');
    Route::get('deletePeriod/{id}', 'ErpPeriodController@deletePeriod');

// Base group routes
    Route::resource('base_group', 'ErpBaseGroupController');
    Route::get('deleteBaseGroupView/{id}', 'ErpBaseGroupController@deleteBaseGroupView');
    Route::get('deleteBaseGroup/{id}', 'ErpBaseGroupController@deleteBaseGroup');

// Base setup routes
    Route::resource('base_setup', 'ErpBaseSetupController');
    Route::get('deleteBaseSetupView/{id}', 'ErpBaseSetupController@deleteBaseSetupView');
    Route::get('deleteBaseSetup/{id}', 'ErpBaseSetupController@deleteBaseSetup');

// Designation routes
    Route::resource('designation', 'ErpDesignationController');
    Route::get('deleteDesignationView/{id}', 'ErpDesignationController@deleteDesignationView');
    Route::get('deleteDesignation/{id}', 'ErpDesignationController@deleteDesignation');

// Department routes
    Route::resource('department', 'ErpDepartmentController');
    Route::get('deleteDepartmentView/{id}', 'ErpDepartmentController@deleteDepartmentView');
    Route::get('deleteDepartment/{id}', 'ErpDepartmentController@deleteDepartment');

// Employee routes
    Route::resource('employee', 'ErpEmployeeController');
    Route::get('deleteEmployeeView/{id}', 'ErpEmployeeController@deleteEmployeeView');
    Route::get('deleteEmployee/{id}', 'ErpEmployeeController@deleteEmployee');
    Route::get('checkDuplicateEmail','ErpEmployeeController@checkDuplicateEmail');

// Module links routes
    Route::resource('module_link', 'ErpModuleLinksController');
    Route::get('deleteModuleLinkView/{id}', 'ErpModuleLinksController@deleteModuleLinkView');
    Route::get('deleteModuleLink/{id}', 'ErpModuleLinksController@deleteModuleLink');

    Route::get('coa_view', 'ErpChartOfAccountsController@coa_view');
    Route::get('addAccountModal/{parentId?}','ErpChartOfAccountsController@showAddAccountModal');

// Transaction routes

    Route::get('add_transactions/{transactionType?}','TransactionsController@index')->name('addTransactionView');
    Route::post('get_transactions_form','TransactionsController@index');
    Route::post('add_transactions',[
        'as' => 'addTransactions',
        'uses'=>'TransactionsController@addTransactions'
    ]);

    //Route for trail balance
    Route::get('trial_balance','ReportController@generateTrialBalance');

    // Leave type
    Route::resource('leave_type', 'ErpLeaveTypeController');
    Route::get('deleteLeaveTypeView/{id}', 'ErpLeaveTypeController@deleteLeaveTypeView');
    Route::get('deleteLeaveType/{id}', 'ErpLeaveTypeController@deleteLeaveType');

    // Leave request
    Route::resource('leave_request', 'ErpLeaveRequestController');
    Route::get('deleteLeaveRequestView/{id}', 'ErpLeaveRequestController@deleteLeaveRequestView');
    Route::get('deleteLeaveRequest/{id}', 'ErpLeaveRequestController@deleteLeaveRequest');

});

resources/views/backEnd/employees/employee/create.blade.php
@extends('backEnd.master')
@section('mainContent')
<div class="card">
	<div class="card-header">
		<h5>Add Employee</h5>
	</div>
	<div class="card-block">
		{{ Form::open(['class' => '', 'files' => true, 'url' => 'employee', 'method' => 'POST', 'enctype' => 'multipart/form-data', 'autocomplete' => 'off']) }}
		<input type="hidden" name="url" id="url" value="{{URL::to('/')}}">
			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="first_name">First Name:</label>
				  	<input type="text" class="form-control  {{ $errors->has('first_name') ? ' is-invalid' : '' }}" value="{{ old('first_name') }}" name="first_name" />
				  	@if ($errors->has('first_name'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('first_name') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-6">
				  	<label for="last_name">Last Name:</label>
				  	<input type="text" class="form-control {{ $errors->has('last_name') ? ' is-invalid' : '' }}" value="{{ old('last_name') }}" name="last_name"/>
				  	@if ($errors->has('last_name'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('last_name') }}</strong></span>
						</span>
					@endif
				</div>
				
			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="email">Email:</label>
				  	<input id="email" type="email" class="form-control employee_email {{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}" name="email"/>
				  	@if ($errors->has('email'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('email') }}</strong></span>
						</span>
					@endif
				</div>
				
				<div class="form-group col-md-6">
				  	<label for="employee_photo">Employee Image:</label><br>
				  	<input data-preview="#preview" name="employee_photo" type="file" id="employee_photo">
        			<img class="col-sm-6" id="preview"  src="">
        			<p>* Image format must be png, jpg, jpeg, gif, tiff , svg format and image size must be less than 5mb</p>
				  	@if ($errors->has('employee_photo'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('employee_photo') }}</strong></span>
						</span>
					@endif
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-3">
				  <label for="mobile">Cell no:</label>
				  <input type="text" class="form-control {{ $errors->has('mobile') ? ' is-invalid' : '' }}" value="{{ old('mobile') }}" name="mobile"/>
				  	@if ($errors->has('mobile'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('mobile') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="emergency_no">Emergency no:</label>
				  	<input type="text" class="form-control {{ $errors->has('emergency_no') ? ' is-invalid' : '' }}" value="{{ old('emergency_no') }}" name="emergency_no"/>
				  	@if ($errors->has('emergency_no'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('emergency_no') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="date_of_birth">Date of birth:</label>
				  	<input type="" class="form-control datepicker {{ $errors->has('date_of_birth') ? ' is-invalid' : '' }}" value="{{ old('date_of_birth') }}" name="date_of_birth"/>
				  	@if ($errors->has('date_of_birth'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('date_of_birth') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="joining_date">Joining date:</label>
				  	<input type="" class="form-control datepicker {{ $errors->has('joining_date') ? ' is-invalid' : '' }}" value="{{ old('joining_date') }}" name="joining_date"/>
				  	@if ($errors->has('joining_date'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('joining_date') }}</strong></span>
						</span>
					@endif
				</div>

			</div>
			

			<div class="row">

				<div class="form-group col-md-3">
				  	<label for="department_id">Department name:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('department_id') ? ' is-invalid' : '' }}" name="department_id" id="department_id">
					<option value="">Select Dept.</option>
					@if(isset($departments))
						@foreach($departments as $department)
							<option value="{{ $department->id }}" {{ old('department_id')== $department->id ? 'selected' : old('department_id')  }} >{{$department->department_name}}</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('department_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('department_id') }}</strong>
					</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="designation_id">Designation name:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('designation_id') ? ' is-invalid' : '' }}" name="designation_id" id="designation_id">
					<option value="">Select Designation</option>
					@if(isset($designations))
						@foreach($designations as $designation)
							<option value="{{ $designation->id }}" {{ old('designation_id')== $designation->id ? 'selected' : old('designation_id')  }} >{{$designation->designation_name}}</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('designation_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('designation_id') }}</strong>
					</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="gender_id">Gender:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('gender_id') ? ' is-invalid' : '' }}" name="gender_id" id="gender_id">
					<option value="">Select gender</option>
					@if(isset($genders))
						@foreach($genders as $gender)
							<option value="{{ $gender->id }}" {{ old('gender_id')== $gender->id ? 'selected' : old('gender_id')  }} >{{$gender->base_setup_name}}</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('gender_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('gender_id') }}</strong>
					</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="blood_group_id">Blood group:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('blood_group_id') ? ' is-invalid' : '' }}" name="blood_group_id" id="blood_group_id">
					<option value="">Select group</option>
					@if(isset($blood_groups))
						@foreach($blood_groups as $blood_group)
							<option value="{{ $blood_group->id }}" {{ old('blood_group')== $blood_group->id ? 'selected' : old('blood_group')  }} >{{$blood_group->base_setup_name}}</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('blood_group_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('blood_group_id') }}</strong>
					</span>
					@endif
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="permanent_address">Permanent address:</label>
				  	<textarea class="form-control" value="{{ old('permanent_address') }}" name="permanent_address"></textarea>
				</div>

				<div class="form-group col-md-6">
				  	<label for="current_address">Current address:</label>
				  	<textarea class="form-control" value="{{ old('current_address') }}" name="current_address"></textarea>
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="qualifications">Qualifications:</label>
				  	<textarea class="form-control" value="{{ old('qualifications') }}" name="qualifications"></textarea>
				</div>

				<div class="form-group col-md-6">
				  	<label for="experiences">Experiences:</label>
				  	<textarea class="form-control" value="{{ old('experiences') }}" name="experiences"></textarea>
				</div>

			</div>

			<div class="form-group row mt-5">
				<div class="col-sm-12 text-center">
					<button type="submit" class="btn btn-primary m-b-0">Add Employee</button>
				</div>
			</div>
		{{ Form::close()}}
	</div>
</div>

@endSection

@section('javascript')

	<script src="{{asset('public/js/addEmployee.js')}}"></script>

@endsection

resources/views/backEnd/employees/employee/edit.blade.php
@extends('backEnd.master')
@section('mainContent')
<div class="card">
	<div class="card-header">
		<h5>Edit Employee</h5>
	</div>
	<div class="card-block">
		{{ Form::open(['class' => '', 'files' => true, 'url' => 'employee/'.$editData->id, 'method' => 'PUT', 'enctype' => 'multipart/form-data', 'autocomplete' => 'off']) }}
			<div class="row">
				<div class="form-group col-md-6">
				  	
				</div>

				<div class="form-group col-md-6">
				  	@if( isset($editData->employee_photo) )
						<img src="{{ asset($editData->employee_photo) }}" class="image_center img-radius" height="200px" width="200px" />
					@else
						<img src="{{ asset('/public/images/no_image.png') }}" class="image_center img-radius" height="200px" width="200px" />
					@endif
				</div>
			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="first_name">First Name:</label>
				  	<input type="text" class="form-control  {{ $errors->has('first_name') ? ' is-invalid' : '' }}" value="{{$editData->first_name}}" name="first_name" />
				  	@if ($errors->has('first_name'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('first_name') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-6">
				  	<label for="last_name">Last Name:</label>
				  	<input type="text" class="form-control {{ $errors->has('last_name') ? ' is-invalid' : '' }}" value="{{$editData->last_name}}" name="last_name"/>
				  	@if ($errors->has('last_name'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('last_name') }}</strong></span>
						</span>
					@endif
				</div>
				
			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="email">Email:</label>
				  	<input type="email" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{$editData->email}}" name="email"/>
				  	@if ($errors->has('email'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('email') }}</strong></span>
						</span>
					@endif
				</div>
				
				<div class="form-group col-md-6">
				  	<label for="employee_photo">Employee Image:</label><br>
				  	<input data-preview="#preview" name="employee_photo" type="file" id="employee_photo">
				  	<p>* Image format must be png, jpg, jpeg, gif, tiff , svg format and image size must be less than 5mb</p>
				  	@if ($errors->has('employee_photo'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('employee_photo') }}</strong></span>
						</span>
					@endif
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-3">
				  <label for="mobile">Cell no:</label>
				  <input type="text" class="form-control {{ $errors->has('mobile') ? ' is-invalid' : '' }}" value="{{$editData->mobile}}" name="mobile"/>
				  	@if ($errors->has('mobile'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('mobile') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="emergency_no">Emergency no:</label>
				  	<input type="text" class="form-control {{ $errors->has('emergency_no') ? ' is-invalid' : '' }}" value="{{$editData->emergency_no }}" name="emergency_no"/>
				  	@if ($errors->has('emergency_no'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('emergency_no') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="date_of_birth">Date of birth:</label>
				  	<input type="" class="form-control datepicker {{ $errors->has('date_of_birth') ? ' is-invalid' : '' }}" 
				  	@if(isset($editData->date_of_birth)) 
				  		value="{{ date('d-m-Y', strtotime($editData->date_of_birth)) }}"
				  	@endif
				  	name="date_of_birth"/>
				  	@if ($errors->has('date_of_birth'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('date_of_birth') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="joining_date">Joining date:</label>
				  	<input type="" class="form-control datepicker {{ $errors->has('joining_date') ? ' is-invalid' : '' }}"
				  	@if(isset($editData->date_of_birth)) 
				  		value="{{ date('d-m-Y', strtotime($editData->date_of_birth)) }}"
				  	@endif 
				  	name="joining_date"/>
				  	@if ($errors->has('joining_date'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('joining_date') }}</strong></span>
						</span>
					@endif
				</div>

			</div>
			

			<div class="row">

				<div class="form-group col-md-3">
				  	<label for="department_id">Department name:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('department_id') ? ' is-invalid' : '' }}" name="department_id" id="department_id">
					<option value="">Select Dept.</option>
					@if(isset($departments))
						@foreach($departments as $key=>$value)
							<option value="{{$value->id}}"
								@if(isset($editData))
									@if($editData->department_id == $value->id)
										selected
									@endif
								@endif
								>{{$value->department_name}}
							</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('department_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('department_id') }}</strong>
					</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="designation_id">Designation name:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('designation_id') ? ' is-invalid' : '' }}" name="designation_id" id="designation_id">
					<option value="">Select Designation</option>
					@if(isset($designations))
						@foreach($designations as $key=>$value)
							<option value="{{$value->id}}"
								@if(isset($editData))
									@if($editData->designation_id == $value->id)
										selected
									@endif
								@endif
								>{{$value->designation_name}}
							</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('designation_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('designation_id') }}</strong>
					</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="gender_id">Gender:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('gender_id') ? ' is-invalid' : '' }}" name="gender_id" id="gender_id">
					<option value="">Select gender</option>
					@if(isset($genders))
						@foreach($genders as $key=>$value)
							<option value="{{$value->id}}"
								@if(isset($editData))
									@if($editData->gender_id == $value->id)
										selected
									@endif
								@endif
								>{{$value->base_setup_name}}
							</option>						
						@endforeach
					@endif
					</select>
					@if ($errors->has('gender_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('gender_id') }}</strong>
					</span>
					@endif
				</div>

				<div class="form-group col-md-3">
				  	<label for="blood_group_id">Blood group:</label>
				  	<select class="js-example-basic-single col-sm-12 {{ $errors->has('blood_group_id') ? ' is-invalid' : '' }}" name="blood_group_id" id="blood_group_id">
					<option value="">Select group</option>
					@if(isset($blood_groups))
						@foreach($blood_groups as $key=>$value)
							<option value="{{$value->id}}"
								@if(isset($editData))
									@if($editData->blood_group_id == $value->id)
										selected
									@endif
								@endif
								>{{$value->base_setup_name}}
							</option>						
						@endforeach
					@endif
					</select>
					@if ($errors->has('blood_group_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('blood_group_id') }}</strong>
					</span>
					@endif
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="permanent_address">Permanent address:</label>
				  	<textarea class="form-control" value="" name="permanent_address">{{  $editData->permanent_address }}</textarea>
				</div>

				<div class="form-group col-md-6">
				  	<label for="current_address">Current address:</label>
				  	<textarea class="form-control" value="" name="current_address">{{  $editData->current_address }}</textarea>
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="qualifications">Qualifications:</label>
				  	<textarea class="form-control" value="" name="qualifications">{{  $editData->qualifications }}</textarea>
				</div>

				<div class="form-group col-md-6">
				  	<label for="experiences">Experiences:</label>
				  	<textarea class="form-control" value="" name="experiences">{{  $editData->experiences }}</textarea>
				</div>

			</div>

			<div class="form-group row mt-5">
				<div class="col-sm-12 text-center">
					<button type="submit" class="btn btn-primary m-b-0">Update Employee</button>
				</div>
			</div>		  
		{{ Form::close()}}
	</div>
</div>

@endSection

resources/views/backEnd/employees/employee/index.blade.php
@extends('backEnd.master')
@section('mainContent')

@if(session()->has('message-success'))
<div class="alert alert-success mb-3 background-success" role="alert">
	{{ session()->get('message-success') }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
@elseif(session()->has('message-danger'))
<div class="alert alert-danger">
	{{ session()->get('message-danger') }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
@endif
@if(session()->has('message-success-delete'))
<div class="alert alert-danger mb-3 background-danger" role="alert">
	{{ session()->get('message-success-delete') }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
@elseif(session()->has('message-danger-delete'))
<div class="alert alert-danger">
	{{ session()->get('message-danger-delete') }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
@endif


<div class="card">
	<div class="card-header">
		<h5>Employee Lists</h5>
		<a href="{{ route('employee.create') }}" style="float: right; padding: 8px;" class="btn btn-success"> Add Employee </a>
	</div>
	<div class="card-block">
		<table id="basic-btn" class="table table-striped table-bordered nowrap">
			<thead>
				<tr>
					<th>Serial</th>
					<th>Photo</th>
					<th>Full Name</th>
					<th>Mobile</th>
					<th>Email</th>
					<th>Joining date</th>
					<th>Department</th>
					<th>Designation</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@php $i = 1 @endphp
				@foreach($employees as $employee)
				<tr>
					<td>{{$i++}}</td>
					<td>
						<div class="d-inline-block align-middle">
							@if(empty($employee->employee_photo))
							<img src="{{asset('public/images/no_image.png')}}" alt="user image" class="img-radius img-40 align-top m-r-15">
							@else
							<img src="{{asset($employee->employee_photo)}}" alt="user image" class="img-radius img-40 align-top m-r-15">
							@endif
						</div>
					</td>
					<td>{{$employee->full_name}}</td>
					<td>{{$employee->mobile}}</td>
					<td>{{$employee->email}}</td>
					<td>{{date('d-M-Y', strtotime($employee->joining_date))}}</td>
					<td>
						@if(isset($employee->department_id))
						{{$employee->department->department_name}}
						@endif
					</td>
					<td>
						@if(isset($employee->designation_id))
						{{$employee->designation->designation_name}}
						@endif
					</td>
					
					<td>
						<a href="{{ route('employee.show',$employee->id) }}" title="view"><button type="button" class="btn btn-success action-icon"><i class="fa fa-eye"></i></button></a>
						<a href="{{ route('employee.edit',$employee->id) }}" title="edit"><button type="button" class="btn btn-info action-icon"><i class="fa fa-edit"></i></button></a>
						<a class="modalLink" title="Delete" data-modal-size="modal-md" href="{{url('deleteEmployeeView', $employee->id)}}">
							<button type="button" class="btn btn-danger action-icon"><i class="fa fa-trash-o"></i></button>
						</a>
					</td>

				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>
@endSection