routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['revalidate','auth']], function(){
	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index');
	Route::get('/dashboard', 'HomeController@index');


    // project
    Route::resource('project', 'ErpProjectController');
    Route::get('deleteProjectView/{id}', 'ErpProjectController@deleteProjectView');
    Route::get('deleteProject/{id}', 'ErpProjectController@deleteProject');

//Chart of Accounts Category
    Route::resource('account-category', 'ErpAccountsCategoryController');
    Route::get('deleteAccountCategoryView/{id}', 'ErpAccountsCategoryController@deleteAccountCategoryView');
    Route::get('deleteAccountCategory/{id}', 'ErpAccountsCategoryController@deleteAccountCategory');

//chart of Accounts Class
    Route::resource('account-class', 'ErpAccountsClassController');
    Route::get('deleteAccountClassView/{id}', 'ErpAccountsClassController@deleteAccountClassView');
    Route::get('deleteAccountClass/{id}', 'ErpAccountsClassController@deleteAccountClass');

// Chart of Accounts
    Route::get('account-list', 'ErpChartOfAccountsController@accountList');
    Route::get('add-new-coa', 'ErpChartOfAccountsController@addNewCoa');
    Route::post('save-coa-data', 'ErpChartOfAccountsController@saveCoaData');
    Route::get('edit-coa/{id}', 'ErpChartOfAccountsController@editCoa');
    Route::post('editCoa', 'ErpChartOfAccountsController@editCoa');


//Client route
    Route::resource('client', 'ErpClientController');
    Route::get('deleteClientView/{id}', 'ErpClientController@deleteClientView');
    Route::get('deleteClient/{id}', 'ErpClientController@deleteClient');

// Role route
    Route::resource('role', 'ErpRoleController');
    Route::get('deleteRoleView/{id}', 'ErpRoleController@deleteRoleView');
    Route::get('deleteRole/{id}', 'ErpRoleController@deleteRole');
    Route::get('assign-permission/{role_id}', 'ErpRoleController@assignPermission');
    Route::post('role_permission_store', 'ErpRoleController@rolePermissionStore');

// User route
    Route::resource('user', 'ErpUserController');
    Route::get('deleteUserView/{id}', 'ErpUserController@deleteUserView');
    Route::get('deleteUser/{id}', 'ErpUserController@deleteUser');

//chart of Accounts Period
    Route::resource('period', 'ErpPeriodController');
    Route::get('deletePeriodView/{id}', 'ErpPeriodController@deletePeriodView');
    Route::get('deletePeriod/{id}', 'ErpPeriodController@deletePeriod');

// Base group routes
    Route::resource('base_group', 'ErpBaseGroupController');
    Route::get('deleteBaseGroupView/{id}', 'ErpBaseGroupController@deleteBaseGroupView');
    Route::get('deleteBaseGroup/{id}', 'ErpBaseGroupController@deleteBaseGroup');

// Base setup routes
    Route::resource('base_setup', 'ErpBaseSetupController');
    Route::get('deleteBaseSetupView/{id}', 'ErpBaseSetupController@deleteBaseSetupView');
    Route::get('deleteBaseSetup/{id}', 'ErpBaseSetupController@deleteBaseSetup');

// Designation routes
    Route::resource('designation', 'ErpDesignationController');
    Route::get('deleteDesignationView/{id}', 'ErpDesignationController@deleteDesignationView');
    Route::get('deleteDesignation/{id}', 'ErpDesignationController@deleteDesignation');

// Department routes
    Route::resource('department', 'ErpDepartmentController');
    Route::get('deleteDepartmentView/{id}', 'ErpDepartmentController@deleteDepartmentView');
    Route::get('deleteDepartment/{id}', 'ErpDepartmentController@deleteDepartment');

// Employee routes
    Route::resource('employee', 'ErpEmployeeController');
    Route::get('deleteEmployeeView/{id}', 'ErpEmployeeController@deleteEmployeeView');
    Route::get('deleteEmployee/{id}', 'ErpEmployeeController@deleteEmployee');
    Route::get('checkDuplicateEmail','ErpEmployeeController@checkDuplicateEmail');

// Module links routes
    Route::resource('module_link', 'ErpModuleLinksController');
    Route::get('deleteModuleLinkView/{id}', 'ErpModuleLinksController@deleteModuleLinkView');
    Route::get('deleteModuleLink/{id}', 'ErpModuleLinksController@deleteModuleLink');

    Route::get('coa_view', 'ErpChartOfAccountsController@coa_view');
    Route::get('addAccountModal/{parentId?}','ErpChartOfAccountsController@showAddAccountModal');

// Transaction routes

    Route::get('add_transactions/{transactionType?}','TransactionsController@index')->name('addTransactionView');
    Route::post('get_transactions_form','TransactionsController@index');
    Route::post('add_transactions',[
        'as' => 'addTransactions',
        'uses'=>'TransactionsController@addTransactions'
    ]);

    //Route for trail balance
    Route::get('trial_balance','ReportController@generateTrialBalance');

    // Leave type
    Route::resource('leave_type', 'ErpLeaveTypeController');
    Route::get('deleteLeaveTypeView/{id}', 'ErpLeaveTypeController@deleteLeaveTypeView');
    Route::get('deleteLeaveType/{id}', 'ErpLeaveTypeController@deleteLeaveType');

    // Leave request
    Route::resource('leave_request', 'ErpLeaveRequestController');
    Route::get('deleteLeaveRequestView/{id}', 'ErpLeaveRequestController@deleteLeaveRequestView');
    Route::get('deleteLeaveRequest/{id}', 'ErpLeaveRequestController@deleteLeaveRequest');

});

resources/views/backEnd/employees/leave_request/create.blade.php
@extends('backEnd.master')
@section('mainContent')
<div class="card">
	<div class="card-header">
		<h5>Add Leave Request</h5>
	</div>
	<div class="card-block">
		{{ Form::open(['class' => '', 'files' => true, 'url' => 'leave_request', 'method' => 'POST', 'enctype' => 'multipart/form-data', 'autocomplete' => 'off']) }}

			<div class="row">
				
				<div class="form-group col-md-6">
					<label class="col-form-label">Leave Type</label>
					<select class="js-example-basic-single col-sm-12 {{ $errors->has('type_id') ? ' is-invalid' : '' }}" name="type_id" id="type_id">
					<option value="">Select Leave Type</option>
					@if(isset($leave_types))
						@foreach($leave_types as $leave_type)
							<option value="{{ $leave_type->id }}"  {{ old('leave_type')== $leave_type->id ? 'selected' : ''  }}>{{$leave_type->type}}</option>
						@endforeach
					@endif
					</select>
					@if ($errors->has('type_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('type_id') }}</strong>
					</span>
					@endif
				</div>
				
				<div class="form-group col-md-6">
				  	<label for="apply_date">Apply Date :</label>
				  	<input type="" class="form-control datepicker  {{ $errors->has('apply_date') ? ' is-invalid' : '' }}" value="{{ old('apply_date') }}" name="apply_date"/>
				  	@if ($errors->has('apply_date'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('apply_date') }}</strong></span>
						</span>
					@endif
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="leave_from">Leave From:</label>
				  	<input type="" class="form-control datepicker  {{ $errors->has('leave_from') ? ' is-invalid' : '' }}" value="{{ old('leave_from') }}" name="leave_from"/>
				  	@if ($errors->has('leave_from'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('leave_from') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-6">
				  	<label for="leave_to">Leave To:</label>
				  	<input type="" class="form-control datepicker  {{ $errors->has('leave_to') ? ' is-invalid' : '' }}" value="{{ old('leave_to') }}" name="leave_to"/>
				  	@if ($errors->has('leave_to'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('leave_to') }}</strong></span>
						</span>
					@endif
				</div>
				
			</div>

			<div class="row">

				<div class="form-group col-md-6">
				  	<label for="reason">Reason:</label>
				  	<textarea class="form-control" value="{{ old('reason') }}" name="reason"></textarea>
				  	
				  	@if ($errors->has('reason'))
					    <span class="" role="alert" >
							<span class="messages add_customized_red_error"><strong>{{ $errors->first('reason') }}</strong></span>
						</span>
					@endif
				</div>
				<div class="form-group col-md-6">
				  	<label for="reason">Upload File:</label><br>
				  	<input type="file" name="file" id="file">
				  	<br>
				  	<p>* Valid extensions are pdf, png, jpg, jpeg, doc, docx, gif, tiff, svg and file must be less then 9 MB.</p>
				</div>

			</div>

			<div class="form-group row mt-5">
				<div class="col-sm-12 text-center">
					<button type="submit" class="btn btn-primary m-b-0">Add Request</button>
				</div>
			</div>
		{{ Form::close()}}
	</div>
</div>

@endSection

resources/views/backEnd/employees/leave_request/edit.blade.php
@extends('backEnd.master')
@section('mainContent')
<div class="card">
	<div class="card-header">
		<h5>Edit Leave Request</h5>
	</div>
	<div class="card-block">
		{{ Form::open(['class' => '', 'files' => true, 'url' => 'leave_request/'.$editData->id, 'method' => 'PUT', 'enctype' => 'multipart/form-data', 'autocomplete' => 'off']) }}

			<div class="row">
				
				<div class="form-group col-md-6">
					<label class="col-form-label">Leave Type</label>
					<select class="js-example-basic-single col-sm-12 {{ $errors->has('type_id') ? ' is-invalid' : '' }}" name="type_id" id="type_id">
					<option value="">Select Leave Type</option>
					@if(isset($leave_types))
						@foreach($leave_types as $leave_type)
							@if ($leave_type->id == $editData->type_id)
								<option value="{{ $leave_type->id }}"  selected="selected">{{$leave_type->type}}</option>
							@else
								<option value="{{ $leave_type->id }}" >{{$leave_type->type}}</option>
							@endif
						@endforeach
					@endif
					</select>
					@if ($errors->has('type_id'))
					<span class="invalid-feedback invalid-select" role="alert">
						<strong>{{ $errors->first('type_id') }}</strong>
					</span>
					@endif
				</div>
				
				<div class="form-group col-md-6">
				  	<label for="apply_date">Apply Date :</label>
				  	<input type="" class="form-control datepicker  {{ $errors->has('apply_date') ? ' is-invalid' : '' }}" name="apply_date"
				  	@if(isset($editData->apply_date)) 
				  		value="{{ date('d-m-Y', strtotime($editData->apply_date)) }}"
				  	@endif
				  	/>
				  	@if ($errors->has('apply_date'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('apply_date') }}</strong></span>
						</span>
					@endif
				</div>

			</div>

			<div class="row">
				
				<div class="form-group col-md-6">
				  	<label for="leave_from">Leave From:</label>
				  	<input type="" class="form-control datepicker  {{ $errors->has('leave_from') ? ' is-invalid' : '' }}"
				  	@if(isset($editData->leave_from)) 
				  		value="{{ date('d-m-Y', strtotime($editData->leave_from)) }}"
				  	@endif
				  	name="leave_from"/>
				  	@if ($errors->has('leave_from'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('leave_from') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-6">
				  	<label for="leave_to">Leave To:</label>
				  	<input type="" class="form-control datepicker  {{ $errors->has('leave_to') ? ' is-invalid' : '' }}" 
				  	@if(isset($editData->leave_to)) 
				  		value="{{ date('d-m-Y', strtotime($editData->leave_to)) }}"
				  	@endif
				  	name="leave_to"/>
				  	@if ($errors->has('leave_to'))
					    <span class="invalid-feedback" role="alert" >
							<span class="messages"><strong>{{ $errors->first('leave_to') }}</strong></span>
						</span>
					@endif
				</div>
				
			</div>

			<div class="row">

				<div class="form-group col-md-6">
				  	<label for="reason">Reason:</label>
				  	<textarea class="form-control" value="{{ old('reason') }}" name="reason">{{  $editData->reason }}</textarea>
				  	@if ($errors->has('reason'))
					    <span class="" role="alert" >
							<span class="messages add_customized_red_error"><strong>{{ $errors->first('reason') }}</strong></span>
						</span>
					@endif
				</div>

				<div class="form-group col-md-6">
				  	<label for="reason">Upload File:</label> <br>
				  	<input type="file" name="file" id="file">
				  	<p>* Valid extensions are pdf, png, jpg, jpeg, doc, docx, gif, tiff, svg and file must be less then 9 MB.</p>
				</div>

			</div>

			<div class="form-group row mt-5">
				<div class="col-sm-12 text-center">
					<button type="submit" class="btn btn-primary m-b-0">Update Request</button>
				</div>
			</div>
		{{ Form::close()}}
	</div>
</div>

@endSection

resources/views/backEnd/employees/leave_request/index.blade.php
@extends('backEnd.master')
@section('mainContent')

@if(session()->has('message-success'))
	<div class="alert alert-success mb-3 background-success" role="alert">
		{{ session()->get('message-success') }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@elseif(session()->has('message-danger'))
	<div class="alert alert-danger">
		{{ session()->get('message-danger') }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif
@if(session()->has('message-success-delete'))
	<div class="alert alert-danger mb-3 background-danger" role="alert">
		{{ session()->get('message-success-delete') }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@elseif(session()->has('message-danger-delete'))
	<div class="alert alert-danger">
		{{ session()->get('message-danger-delete') }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif


<div class="card">
	<div class="card-header">
		<h5>Leave Request Lists</h5>
		<a href="{{ route('leave_request.create') }}" style="float: right; padding: 8px;" class="btn btn-success"> Add Leave Request </a>
	</div>
	@if ($user_role_id == 1)
		<div class="card-block">
			<table id="basic-btn" class="table table-striped table-bordered nowrap">
				<thead>
					<tr>
						<th>Serial</th>
						<th>Leave Type Name</th>
						<th>Applied at</th>
						<th>From</th>
						<th>To</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@php $i = 1 @endphp
					@foreach($leave_requests as $leave_request)
			        <tr>
			            <td>{{$i++}}</td>
			            @if ( isset($leave_types) )
			            	@foreach ($leave_types as $leave_type) 
			            		@if ($leave_type->id == $leave_request->type_id)
			            			<td>{{$leave_type->type}}</td>
			            		@endif
			            	@endforeach
			            @else
			            	<td>No types</td>
			            @endif

			            <td>{{ date('d-M-Y', strtotime($leave_request->apply_date)) }}</td>
			            <td>{{ date('d-M-Y', strtotime($leave_request->leave_from)) }}</td>
			            <td>{{ date('d-M-Y', strtotime($leave_request->leave_to)) }}</td>
			            @if ($user_role_id == 1)
			            	<td>
								<a href="{{ route('leave_request.show',$leave_request->id) }}" title="view"><button type="button" class="btn btn-success action-icon"><i class="fa fa-eye"></i></button></a>
								<a class="modalLink" title="Delete" data-modal-size="modal-md" href="{{url('deleteLeaveRequestView', $leave_request->id)}}">
									<button type="button" class="btn btn-success action-icon">Accept</button>
								</a>
								<a class="modalLink" title="Delete" data-modal-size="modal-md" href="{{url('deleteLeaveRequestView', $leave_request->id)}}">
									<button type="button" class="btn btn-danger action-icon">Reject</button>
								</a>
				            </td>
			            @else
			            	<td>
								<a href="{{ route('leave_request.edit',$leave_request->id) }}" title="edit"><button type="button" class="btn btn-info action-icon"><i class="fa fa-edit"></i></button></a>
								<a class="modalLink" title="Delete" data-modal-size="modal-md" href="{{url('deleteLeaveRequestView', $leave_request->id)}}">
									<button type="button" class="btn btn-danger action-icon"><i class="fa fa-trash-o"></i></button>
								</a>
				            </td>
			            @endif
			            
			            
			        </tr>
			        @endforeach
				</tbody>
				<tfoot>
					<tr>
						<th>Serial</th>
						<th>Leave Type Name</th>
						<th>Applied at</th>
						<th>From</th>
						<th>To</th>
						<th>Actions</th>
					</tr>
				</tfoot>
			</table>
		</div>
	@else
		<div class="card-block">
			<table id="basic-btn" class="table table-striped table-bordered nowrap">
				<thead>
					<tr>
						<th>Serial</th>
						<th>Leave Type Name</th>
						<th>Applied at</th>
						<th>From</th>
						<th>To</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@php $i = 1 @endphp
					@foreach($leave_requests as $leave_request)
			        <tr>
			            <td>{{$i++}}</td>
			            @if ( isset($leave_types) )
			            	@foreach ($leave_types as $leave_type) 
			            		@if ($leave_type->id == $leave_request->type_id)
			            			<td>{{$leave_type->type}}</td>
			            		@endif
			            	@endforeach
			            @else
			            	<td>No types</td>
			            @endif
			            <td>{{ date('d-M-Y', strtotime($leave_request->apply_date)) }}</td>
			            <td>{{ date('d-M-Y', strtotime($leave_request->leave_from)) }}</td>
			            <td>{{ date('d-M-Y', strtotime($leave_request->leave_to)) }}</td>
		            	<td>
							<a href="{{ route('leave_request.edit',$leave_request->id) }}" title="edit"><button type="button" class="btn btn-info action-icon"><i class="fa fa-edit"></i></button></a>
							<a class="modalLink" title="Delete" data-modal-size="modal-md" href="{{url('deleteLeaveRequestView', $leave_request->id)}}">
								<button type="button" class="btn btn-danger action-icon"><i class="fa fa-trash-o"></i></button>
							</a>
			            </td>         
			        </tr>
			        @endforeach
				</tbody>
				<tfoot>
					<tr>
						<th>Serial</th>
						<th>Leave Type Name</th>
						<th>Applied at</th>
						<th>From</th>
						<th>To</th>
						<th>Actions</th>
					</tr>
				</tfoot>
			</table>
		</div>
	@endif
	
</div>
@endSection